### ISSUE TITLE
Please provide aarch64 binaries in the releases

### ISSUE THREAD

**Issue by krishnakumarg1984** [noamraph/nixsa#15]
Thanks a lot for creating `nixsa`. It is an amazing tool that solves several of my problems with `nix-portable`. With v0.1.2 (have to try the newly released v0.1.3), I have been able to use home-manager (standalone flake) by spawing a `bash` subshell and running nixsa within it like so:

``` bashrc
if ! [ -x "$(command -v nixsa)" ] && [ -x "$HOME/nixsa/bin/nixsa" ]; then
  if [[ $SHLVL -eq 1 ]]; then
    command bash
  else
    exec "$HOME/nixsa/bin/nixsa"
  fi
fi
```
After that every nix command works as usual.
It is working on my x86 laptop and HPC clusters where I have only unpriveleged access as a normal user. However, can you also provide aarch64 binaries so that I can enjoy `nixsa` on an ARM v8 neoverse A64fx HPC?

**Comment by noamraph** [comment]
Hi, thanks for the good words! I added an ARM release for 0.1.3.

(It requires some work, since currently GitHub actions doesn't provide free ARM workers)

**Comment by krishnakumarg1984** [comment]
Thank you. Did you mean the next release will have an Arm binary?
